import Order from '@/components/Order/Order'
import React from 'react'
export const metadata = {
  title: "Orders Page | E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Order />
  </>
}

export default page