import Login from '@/components/Login/Login'
import React from 'react'
export const metadata = {
  title: "Login Page | welcome to E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Login />
  </>
}

export default page