import Categories from '@/components/Categories/Categories'
import React from 'react'
export const metadata = {
  title: "Categories Page | E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Categories />
  </>
}

export default page