import { Ubuntu } from "next/font/google";
import "./globals.css";
import Aside from "@/components/Aside/Aside";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";
import ContextData from "@/Providers/Context/ContextData";
import ThemeProvider from "@/Providers/Tehme/ThemeProvider";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata = {
  title: "E-Commerce Dashboard",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={` ${ubuntu.className} bg-white dark:bg-[#171717]  antialiased`}
      >
        <ContextData>
          <ThemeProvider>
            <Header />

            <div className="flex  items-start  ">
              <Aside />
              <section className="w-full pt-4 min-h-screen mx-auto dark:bg-[#101010] bg-[--main-color]   ">

                <div className="py-2">
                  {children}
                </div>

              </section>
            </div>
          </ThemeProvider>

        </ContextData>
        <Toaster />

      </body>
    </html>
  );
}
