import Product from '@/components/Product/Product'
import React from 'react'
export const metadata = {
  title: "Products Page | E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Product />
  </>
}

export default page