import AddProducts from '@/components/AddProducts/AddProducts'
import React from 'react'
export const metadata = {
  title: "Dashboard | Add Product",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <AddProducts/>
  </>
}

export default page