import Profile from '@/components/Profile/Profile'
import React from 'react'
export const metadata = {
  title: "Profile Page | E-Commerce",
  description: "Generated by create next app",
};
const AdminProfile = () => {
  return (
    <div>
        <Profile/>
    </div>
  )
}

export default AdminProfile