import Changepassword from '@/components/Changepassword/Changepassword'
import React from 'react'
export const metadata = {
  title: "Change Password Page | E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Changepassword/>
  </>
}

export default page