import AddCateogory from '@/components/AddCateogory/AddCateogory'
import React from 'react'

export const metadata = {
  title: "Dashboard | Add Category",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <AddCateogory/>
  </>
}

export default page