import Register from '@/components/Register/Register'
import React from 'react'
export const metadata = {
  title: "Register Page | E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Register />
  </>
}

export default page