import Customers from '@/components/Customers/Customers'
import React from 'react'
export const metadata = {
  title: "Customers Page | E-Commerce",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Customers />
  </>
}

export default page